// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var $$String                = require("bs-platform/lib/js/string.js");
var Hashtbl                 = require("bs-platform/lib/js/hashtbl.js");
var Pervasives              = require("bs-platform/lib/js/pervasives.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function isUnique(input) {
  var result = [/* true */1];
  var map = Hashtbl.create(/* None */0, 26);
  $$String.iter((function (x) {
          var exit = 0;
          var val;
          try {
            val = Hashtbl.find(map, x);
            exit = 1;
          }
          catch (exn){
            if (exn !== Caml_builtin_exceptions.not_found) {
              throw exn;
            }
            
          }
          if (exit === 1) {
            if (val !== 0) {
              result[0] = /* false */0;
            }
            
          }
          return Hashtbl.add(map, x, /* true */1);
        }), input);
  return result[0];
}

Pervasives.print_string(Pervasives.string_of_bool(isUnique("ba")) + "\n");

Pervasives.print_string(Pervasives.string_of_bool(isUnique("ba")) + "\n");

Pervasives.print_string(Pervasives.string_of_bool(isUnique("abcdefg")) + "\n");

Pervasives.print_string(Pervasives.string_of_bool(isUnique("abcdefa")) + "\n");

Pervasives.print_string(Pervasives.string_of_bool(isUnique("abcdefghijklmnopqrstuvwxyz")) + "\n");

Pervasives.print_string(Pervasives.string_of_bool(isUnique("abcdefghijklmnopqrstuvwxyza")));

exports.isUnique = isUnique;
/*  Not a pure module */
